services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
  web:
    image: nginx
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "23457:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
