services:
   nginx:
      image: dhi.io/nginx:1-debian13
      ports:
         - "34567:80"
      volumes:
         - ./templates:/etc/nginx/templates
      environment:
         - NGINX_HOST=foobar.com
         - NGINX_PORT=80
